import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import Providers from "./providers";
import "./global.css";

const BricGro = Bricolage_Grotesque({
  variable: "--font-bric",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Animania - Anime Watching Made Fun",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${BricGro.variable} antialiased`}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
